server:
  port: 8080
spring:
  application:
    name: "AuthenticationApi"
  devtools:
    add-properties: false
logging:
  level:
    org:
      springframework:
        web: "DEBUG"
      boot:
        actuate: TRACE
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus,info"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: "always"
cors:
  allowed-origins: "${CORS}"
routes:
  user:
    paths:
      signUp: "/api/v1/user"
      findByEmail: "/api/v1/user/{email}"
  auth:
    paths:
      login: "/auth/v1/login"
adapters:
  r2dbc:
    host: "${DB_HOST}"
    port: "${DB_PORT}"
    database: "${DB_NAME}"
    schema: "public"
    #username: "${DB_USER}"
    #password: "${DB_PASSWORD}"

aws:
  region: "us-east-1"
  dbSecretName: "${DB_SECRET_NAME}"
  jwtSecretName: "${JWT_SECRET_NAME}"
